workflows:
  android-workflow:
    name: PokerAssistant APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - cd poker_assistant && flutter pub get && flutter build apk --release
    artifacts:
      - poker_assistant/build/app/outputs/flutter-apk/app-release.apk
